remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: D4BL Research Tool
description: AI-powered research and analysis tool for Data for Black Lives
show_downloads: true
google_analytics:
baseurl: "/d4bl-research-tool"

# Navigation
nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Architecture
    url: /architecture
  - title: API Reference
    url: /api-reference 