remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: D4BL Research Tool
description: AI-powered research and analysis tool for Data for Black Lives
show_downloads: true
google_analytics:
baseurl: "/d4bl-research-tool"

# Navigation
nav:
  - title: Home
    url: /d4bl-research-tool/
  - title: Installation
    url: /d4bl-research-tool/installation.html
  - title: Architecture
    url: /d4bl-research-tool/architecture.html
  - title: API Reference
    url: /d4bl-research-tool/api-reference.html